"""add_user_profile_fields

Revision ID: e7309514da6f
Revises: 1a0e23fe226f
Create Date: 2026-01-19 17:08:29.566783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7309514da6f'
down_revision: Union[str, Sequence[str], None] = '1a0e23fe226f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('avatar_path', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('avatar_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_size')
    op.drop_column('users', 'avatar_path')
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###
